"""Rendering: turn a Digest into a newsletter-ready Markdown file and a JSON
sidecar (handy for feeding a dashboard or another tool later).
"""

from __future__ import annotations

import json
from pathlib import Path

from config import settings
from radar.logconf import log
from radar.models import Article, Digest

CATEGORY_LABELS = {
    "regulation": "Regulatory & FDA",
    "clinical_trial": "Clinical Trials",
    "research": "Research & Models",
    "funding": "Funding & Deals",
    "product_launch": "Product Launches",
    "drama": "Controversy & Drama",
    "general": "General",
}

# Order sections by editorial priority, not alphabetically.
CATEGORY_ORDER = [
    "regulation", "clinical_trial", "research", "funding",
    "product_launch", "drama", "general",
]


def _fmt_date(article: Article) -> str:
    return article.published.strftime("%Y-%m-%d") if article.published else "undated"


def _article_line(art: Article) -> str:
    label = CATEGORY_LABELS.get(art.category, art.category.title())
    tags = f" _( {', '.join(art.tags)} )_" if art.tags else ""
    return (
        f"- **[{art.title}]({art.url})**{tags}  \n"
        f"  `score {art.score:.0f}` · {art.source} · {label} · {_fmt_date(art)}  \n"
        f"  {art.best_summary()}"
    )


def render_markdown(digest: Digest, top_n: int = 10) -> str:
    date_str = digest.generated_at.strftime("%Y-%m-%d")
    lines: list[str] = []
    lines.append(f"# Healthcare AI Radar - {date_str}")
    lines.append("")
    lines.append(
        f"_{len(digest.articles)} stories tracked across "
        f"{len(digest.sources_ok)} live sources._"
    )
    lines.append("")

    # ---- Top scoops -------------------------------------------------------- #
    top = digest.top(top_n)
    if top:
        lines.append(f"## Top {len(top)} Scoops")
        lines.append("")
        for art in top:
            lines.append(_article_line(art))
            lines.append("")

    # ---- By category ------------------------------------------------------- #
    grouped = digest.by_category()
    lines.append("## By Category")
    lines.append("")
    for cat in CATEGORY_ORDER:
        items = grouped.get(cat)
        if not items:
            continue
        lines.append(f"### {CATEGORY_LABELS.get(cat, cat.title())} ({len(items)})")
        lines.append("")
        for art in items:
            lines.append(_article_line(art))
            lines.append("")

    # ---- Footer ------------------------------------------------------------ #
    lines.append("---")
    lines.append("")
    if digest.sources_ok:
        lines.append(f"**Sources with new items:** {', '.join(digest.sources_ok)}  ")
    if digest.sources_failed:
        lines.append(
            f"**Sources with no items / unreachable:** "
            f"{', '.join(digest.sources_failed)}  "
        )
    lines.append("")
    lines.append(
        "_Generated by Healthcare AI Radar. Scores are a transparent blend of "
        "source credibility, recency, story type and novelty signals. "
        "Summaries are drawn only from source text._"
    )
    return "\n".join(lines).rstrip() + "\n"


def write_outputs(
    digest: Digest, out_dir: Path | None = None, top_n: int = 10
) -> dict[str, Path]:
    """Write dated + 'latest' Markdown and a JSON sidecar. Returns the paths."""
    out_dir = out_dir or settings.OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    date_str = digest.generated_at.strftime("%Y-%m-%d")

    md = render_markdown(digest, top_n=top_n)
    dated_md = out_dir / f"digest_{date_str}.md"
    latest_md = out_dir / "latest.md"
    json_path = out_dir / f"digest_{date_str}.json"

    dated_md.write_text(md, encoding="utf-8")
    latest_md.write_text(md, encoding="utf-8")
    json_path.write_text(
        json.dumps(digest.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8"
    )

    log.info(f"wrote {dated_md.name}, latest.md and {json_path.name} to {out_dir}")
    return {"markdown": dated_md, "latest": latest_md, "json": json_path}
